### PR TITLE
Add more notice due to Terraform relicensed.

### PR DESCRIPTION
**Pull request by wu-sheng**
@kezhenxu94 @rabajaj0509 Please take a look. We should highlight this relicense risk.
We are good but our end users may not because they are the Terraform users.

### CODE REVIEW

**Comment by kezhenxu94** [comment]
I personally don't want to add that much about Terraform's being relicensed to this repo, because I don't think it affects our end users in this particular repo. the new license should only affect vendors who redistribute Terraform, it doesn't even affect the end users of those vendors, meanwhile, the vendors who are affected by the new license, are not our users, and our real users, are not affected by the new license.

**Comment by wu-sheng** [comment]
Once they are using Terraform, they are affected. Why do you think they are not our users?

Of course, I know you mean that, it is not our fault if they pick Terraform, and violate the BSL such as re-distributing or some kind of competition with HashiCorp. 

This statement is not necessary for sure, it is a NOTICE and a reminder, because people lacking open-source knowledge may think all things in the ASF are Apache 2.0 License, and safe to use.

Anyway, we added this kind of statement for Elasticsearch(license changed), and Grafana plugins(GPL 3, incompatible with APLv2), so here it is again by following our `as kind as possible` tradition.

**Comment by kezhenxu94** [comment]
> Once they are using Terraform, they are affected. Why do you think they are not our users?

https://www.hashicorp.com/license-faq#implications-of-change-for-users

> For end users who are using HashiCorp’s current open source products and new releases using the BSL license for their internal or personal usage, there is no change.

Being kind is definitely good but only when it's necessary, but here adding these "NOTICE" only make users overwhelming in my opinion

**Comment by wu-sheng** [comment]
> For end users who are using HashiCorp’s current open source products and new releases using the BSL license for their internal or personal usage, there is no change.

I don't believe this. The key point of BSL is limiting your use cases and redistribution, which in HashCorp BSL case is, that you can't run a competition with HashCorp when distributing/using Terraform. But how to be called a competitor is determined by HashCorp itself. So you can see the tricky point of BSL.
The term `end user` in their statement actually means you are only using rather than creating business benefits on Terraform. :)

**Pull request merged**
