### PR TITLE
fixed locals in elasticsearch

### PR DESCRIPTION
**Pull request by mayank0202**
Terraform apply and plan both works perfectly

### CODE REVIEW

**Review by kezhenxu94 — APPROVED** [review]
Thanks

**Comment by kezhenxu94** [comment]
Please update the doc

**Comment by mayank0202** [comment]
@kezhenxu94  whats the command for updating docs? i know terraform docs updates the readme i guess

**Comment by kezhenxu94** [comment]
> @kezhenxu94 whats the command for updating docs? i know terraform docs updates the readme i guess

use [terraform-doc](https://github.com/terraform-docs/terraform-docs)

```
terraform-docs markdown table --output-file configurations.md --output-mode inject aws
```

**Comment by mayank0202** [comment]
@kezhenxu94  Done

**Comment by mayank0202** [comment]
@kezhenxu94 Why checks are failing ? any idea?

**Comment by kezhenxu94** [comment]
> @kezhenxu94 Why checks are failing ? any idea?

Checking out the codes failed, I believe this is an incident of GitHub itself,

**Pull request merged**
