### PR TITLE
Add keypair resource to enable access to ec2 instance

### PR DESCRIPTION
**Pull request by rabajaj0509**
This pull request aims to enhance the provisioning process of an EC2 instance by introducing customizable variables. With this PR, users can now define their preferred configurations while creating an EC2 instance. Specifically, it ensures that users with a public key located at `~/.ssh/skywalking-terraform.pub` can successfully create an EC2 instance.

### CODE REVIEW

**Comment by rabajaj0509** [comment]
@kezhenxu94 is there anything I am missing in the process of creating an EC2 instance via Terraform?

**Review by kezhenxu94 — APPROVED** [review]
Generally LGTM, some more improvements might come later after this PR:

1. allow users to add more extra tags to **ALL** resources created by Terraform, this can be done by adding a var in variables.tf. Some enterprises enforces specific tags when creating resources in AWS, otherwise it fails weirdly.
1. we can also add a variable to switch whether creating the key pair or not, this can be especially useful for new installation

**Comment by kezhenxu94** [comment]
@rabajaj0509 if you want me to merge this PR at this time and do the improvements in later PR, please let me know

**Comment by rabajaj0509** [comment]
@kezhenxu94 Let's get this one in. I will make these improvements one at a time in the upcoming pull requests.

**Pull request merged**
